apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-sentiment-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://cisc814-gitea:3000/team-queens/team-queens-gitops.git
    targetRevision: main
    path: apps/ml-sentiment-app/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
